{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "clickhouse-cluster.fullname" . }}
  namespace: {{ .Values.serviceMonitor.namespace | default .Release.Namespace }}
  labels:
    {{- include "clickhouse-cluster.labels" . | nindent 4 }}
    app.kubernetes.io/component: clickhouse
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- $annot := include "clickhouse-cluster.renderAnnotations" (dict "common" .Values.commonAnnotations "extra" nil) }}
  {{- if $annot }}
  annotations:
    {{- $annot | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.serviceMonitor.selector }}
  selector:
    {{- toYaml .Values.serviceMonitor.selector | nindent 4 }}
  {{- else }}
  selector:
    matchLabels:
      app: {{ include "clickhouse-cluster.fullname" . }}-clickhouse
  {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: {{ .Values.serviceMonitor.port }}
      path: {{ .Values.serviceMonitor.path }}
      scheme: {{ .Values.serviceMonitor.scheme }}
      {{- with .Values.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .Values.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      {{- with .Values.serviceMonitor.tlsConfig }}
      tlsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      metricRelabelings:
        - action: replace
          targetLabel: cluster
          replacement: {{ include "clickhouse-cluster.fullname" . | quote }}
        {{- with .Values.serviceMonitor.metricRelabelings }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
