{{- if and .Values.secrets.defaultUserPassword.enabled .Values.secrets.defaultUserPassword.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse-cluster.defaultUserPasswordSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clickhouse-cluster.labels" . | nindent 4 }}
  {{- $annot := include "clickhouse-cluster.renderAnnotations" (dict "common" .Values.commonAnnotations "extra" nil) }}
  {{- if $annot }}
  annotations:
    {{- $annot | nindent 4 }}
  {{- end }}
type: Opaque
data:
  password: {{ .Values.secrets.defaultUserPassword.password | b64enc | quote }}
{{- end }}
