{{- if and .Values.secrets.tls.enabled .Values.secrets.tls.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse-cluster.tlsSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clickhouse-cluster.labels" . | nindent 4 }}
  {{- $annot := include "clickhouse-cluster.renderAnnotations" (dict "common" .Values.commonAnnotations "extra" nil) }}
  {{- if $annot }}
  annotations:
    {{- $annot | nindent 4 }}
  {{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.secrets.tls.cert | b64enc | quote }}
  tls.key: {{ .Values.secrets.tls.key | b64enc | quote }}
  {{- if .Values.secrets.tls.caBundle }}
  ca.crt: {{ .Values.secrets.tls.caBundle | b64enc | quote }}
  {{- end }}
{{- end }}
