{{- if .Values.route.enabled }}
{{- include "clickhouse-cluster.validate" . }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "clickhouse-cluster.fullname" . }}-http
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clickhouse-cluster.labels" . | nindent 4 }}
    app.kubernetes.io/component: clickhouse
    {{- with .Values.route.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- $annot := include "clickhouse-cluster.renderAnnotations" (dict "common" .Values.commonAnnotations "extra" .Values.route.annotations) }}
  {{- if $annot }}
  annotations:
    {{- $annot | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.route.host }}
  host: {{ . | quote }}
  {{- end }}
  to:
    kind: Service
    name: {{ .Values.route.serviceName | default (include "clickhouse-cluster.clickhouseServiceName" .) }}
    weight: 100
  port:
    targetPort: {{ .Values.route.targetPort }}
  {{- with .Values.route.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  wildcardPolicy: {{ .Values.route.wildcardPolicy | default "None" }}
{{- end }}
